# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 613)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 811, 591))
        self.widget.setStyleSheet("background-color: rgb(179, 128, 255);\n"
"background-color: rgb(255, 170, 127);")
        self.widget.setObjectName("widget")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 260, 161, 36))
        self.pushButton_2.setStyleSheet("background-color: rgb(11, 131, 36);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 320, 161, 36))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(204, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_1.setGeometry(QtCore.QRect(40, 130, 41, 51))
        self.textBrowser_1.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 140, 51, 21))
        self.lineEdit_3.setStyleSheet("background-color: rgba(255, 255, 255, 0%);\n"
"border: 0px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_2.setGeometry(QtCore.QRect(170, 130, 41, 51))
        self.textBrowser_2.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 140, 51, 21))
        self.lineEdit_4.setStyleSheet("background-color: rgba(255, 255, 255, 0%);\n"
"border: 0px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_3.setGeometry(QtCore.QRect(290, 130, 41, 51))
        self.textBrowser_3.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(340, 140, 51, 21))
        self.lineEdit_5.setStyleSheet("background-color: rgba(255, 255, 255, 0%);\n"
"border: 0px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 40, 181, 36))
        self.lineEdit.setStyleSheet("font: italic 11pt \"FreeSans\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_4.setGeometry(QtCore.QRect(410, 130, 41, 51))
        self.textBrowser_4.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(460, 140, 51, 21))
        self.lineEdit_6.setStyleSheet("background-color: rgba(255, 255, 255, 0%);\n"
"border: 0px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_5.setGeometry(QtCore.QRect(540, 130, 41, 51))
        self.textBrowser_5.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(590, 140, 51, 21))
        self.lineEdit_7.setStyleSheet("background-color: rgba(255, 255, 255, 0%);\n"
"border: 0px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lcdNumber = QtWidgets.QLCDNumber(self.widget)
        self.lcdNumber.setGeometry(QtCore.QRect(690, 60, 91, 71))
        self.lcdNumber.setStyleSheet("background-color: rgb(217, 255, 112);\n"
"color: rgb(0, 0, 0);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(670, 30, 121, 20))
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setGeometry(QtCore.QRect(400, 270, 411, 231))
        self.plainTextEdit.setStyleSheet("background-color: rgb(252, 224, 255);")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_1.setGeometry(QtCore.QRect(710, 460, 100, 41))
        self.pushButton_1.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border: 1px solid black;")
        self.pushButton_1.setObjectName("pushButton_1")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(130, 390, 101, 41))
        self.plainTextEdit_2.setStyleSheet("border: 0px solid white;")
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "WARNING ON"))
        self.pushButton_3.setText(_translate("MainWindow", "WARNING OFF"))
        self.lineEdit_3.setText(_translate("MainWindow", "CAR 1"))
        self.lineEdit_4.setText(_translate("MainWindow", "CAR 2"))
        self.lineEdit_5.setText(_translate("MainWindow", "CAR 3"))
        self.lineEdit.setText(_translate("MainWindow", "PARKING LOT STATE"))
        self.lineEdit_6.setText(_translate("MainWindow", "CAR 4"))
        self.lineEdit_7.setText(_translate("MainWindow", "CAR 5"))
        self.label.setText(_translate("MainWindow", "Temperature (C)"))
        self.pushButton_1.setText(_translate("MainWindow", "SEND"))
